-- Generado automaticamente por scripts/import-productos.mjs
-- Fuente: EspacioHome_Productos.xlsx (38 productos)
-- Correr en el SQL Editor de Supabase.
--
-- precio_costo y precio_venta quedan en null: la planilla todavia no los tiene completos.
-- foto_1/foto_2 apuntan al bucket publico "productos" en Storage -- subir los archivos
-- con el mismo nombre que figura en la planilla para que las imagenes se vean.

insert into public.productos
  (categoria, seccion, nombre, descripcion, color, talle, material, foto_1, foto_2, whatsapp_link, activo, stock)
values
  ('dormitorio', 'Acolchados', 'Acolchado Liso', 'Acolchado liso de alta calidad, suave y cálido', 'Beige', '2 Plazas', 'Microfibra', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/acolchado_beige_2pl.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Acolchado+Liso', true, null),
  ('dormitorio', 'Acolchados', 'Acolchado Liso', 'Acolchado liso de alta calidad, suave y cálido', 'Gris', '2 Plazas', 'Microfibra', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/acolchado_gris_2pl.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Acolchado+Liso', true, null),
  ('dormitorio', 'Acolchados', 'Acolchado Liso', 'Acolchado liso de alta calidad, suave y cálido', 'Blanco', '1 Plaza', 'Microfibra', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/acolchado_blanco_1pl.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Acolchado+Liso', true, null),
  ('dormitorio', 'Acolchados', 'Acolchado Liso', 'Acolchado liso de alta calidad, suave y cálido', 'Gris', 'King', 'Microfibra', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/acolchado_gris_king.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Acolchado+Liso', true, null),
  ('dormitorio', 'Acolchados', 'Acolchado Suave', 'Acolchado ultra suave con textura premium', 'Gris', '2 Plazas', 'Peluche', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/acolchado_gris_suave_2pl.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Acolchado+Suave', true, null),
  ('dormitorio', 'Colchas', 'Colcha con Flecos', 'Colcha liviana con flecos decorativos, ideal para verano', 'Celeste', '2 Plazas', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/colcha_celeste_flecos.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Colcha+con+Flecos', true, null),
  ('dormitorio', 'Colchas', 'Colcha Tufted', 'Colcha con textura tufted y bordes con flecos', 'Beige', '2 Plazas', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/colcha_beige_tufted_con_almohadon.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Colcha+Tufted', true, null),
  ('dormitorio', 'Colchas', 'Colcha Texturada', 'Colcha con relieve y textura artesanal', 'Gris', '2 Plazas', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/colcha_gris_textura.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Colcha+Texturada', true, null),
  ('dormitorio', 'Colchas', 'Colcha Cuadros', 'Colcha a cuadros estilo moderno, reversible', 'Camel', '2 Plazas', 'Poliéster', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/colcha_cuadros_camel.jpg', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/colcha_cuadros_camel_2.jpg', 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Colcha+Cuadros', true, null),
  ('dormitorio', 'Colchas', 'Colcha con Flecos', 'Colcha liviana con flecos decorativos', 'Beige', '1 Plaza', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/colcha_beige_flecos_sofa.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Colcha+con+Flecos', true, null),
  ('dormitorio', 'Colchas', 'Colcha Texturada', 'Colcha con textura y almohadón decorativo', 'Gris', '1 Plaza', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/colcha_gris_almohadon_detalle.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Colcha+Texturada', true, null),
  ('dormitorio', 'Colchas', 'Colcha Yute', 'Colcha estilo boho con tejido de yute', 'Negro/Natural', '2 Plazas', 'Yute', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/colcha_negro_yute.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Colcha+Yute', true, null),
  ('dormitorio', 'Juego de Sábanas', 'Sábanas Lisas', 'Juego de sábanas liso, suave al tacto', 'Beige', '2 Plazas', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/sabanas_beige_cama.jpg', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/sabanas_beige_cama_2.jpg', 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Sábanas+Lisas', true, null),
  ('dormitorio', 'Juego de Sábanas', 'Sábanas a Rayas', 'Juego de sábanas diseño rayas bicolor', 'Azul/Naranja', '2 Plazas', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/sabanas_rayas_azul_naranja.jpg', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/sabanas_rayas_naranja_cama.jpg', 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Sábanas+a+Rayas', true, null),
  ('dormitorio', 'Juego de Sábanas', 'Sábanas a Rayas', 'Juego de sábanas diseño rayas bicolor', 'Gris', '1 Plaza', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/sabanas_rayas_gris_1pl.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Sábanas+a+Rayas', true, null),
  ('dormitorio', 'Juego de Sábanas', 'Sábanas Blancas', 'Juego de sábanas blancas clásicas', 'Blanco', '2 Plazas', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/sabanas_blancas_cama.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Sábanas+Blancas', true, null),
  ('dormitorio', 'Juego de Sábanas', 'Sábanas Estampadas', 'Juego de sábanas disponible en local', 'Varios', 'Varios', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/sabanas_empaquetadas_local.jpg', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/sabanas_variedad_local.jpg', 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Sábanas+Estampadas', true, null),
  ('dormitorio', 'Fundas Almohadones', 'Funda Bouclé', 'Funda de almohadón textura bouclé, suave y moderna', 'Blanco', '50x70 cm', 'Bouclé', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/funda_boucl%C3%A9_blanca.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Funda+Bouclé', true, null),
  ('dormitorio', 'Fundas Almohadones', 'Funda Tejida', 'Funda de almohadón tejida artesanal', 'Natural', '50x70 cm', 'Algodón tejido', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/funda_tejida_natural.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Funda+Tejida', true, null),
  ('dormitorio', 'Almohadones', 'Almohadón Liso', 'Almohadón decorativo liso con relleno incluido', 'Mostaza', '50x50 cm', 'Lino', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/almohadones_mostaza_blanco_rayas.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Almohadón+Liso', true, null),
  ('dormitorio', 'Almohadones', 'Almohadón Liso', 'Almohadón decorativo liso con relleno incluido', 'Blanco', '50x50 cm', 'Lino', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/almohadones_mostaza_blanco_rayas.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Almohadón+Liso', true, null),
  ('dormitorio', 'Almohadones', 'Almohadón a Rayas', 'Almohadón a rayas decorativo', 'Amarillo/Natural', '50x50 cm', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/almohadones_verdes_amarillos.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Almohadón+a+Rayas', true, null),
  ('dormitorio', 'Almohadones', 'Almohadón Liso', 'Almohadón decorativo liso con relleno incluido', 'Azul', '50x50 cm', 'Lino', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/almohadon_azul_naranja.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Almohadón+Liso', true, null),
  ('dormitorio', 'Almohadones', 'Almohadón Beige', 'Almohadón beige texturado ideal para sofá', 'Beige', '50x50 cm', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/almohadones_beige_sofa.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Almohadón+Beige', true, null),
  ('dormitorio', 'Almohadones', 'Almohadón Tufted', 'Almohadón con bordado tufted geométrico', 'Gris', '50x50 cm', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/almohadon_tufted_gris.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Almohadón+Tufted', true, null),
  ('dormitorio', 'Almohadones', 'Almohadón Tejido', 'Almohadón tejido a mano, estilo boho', 'Blanco', '50x50 cm', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/almohadon_blanco_tejido.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Almohadón+Tejido', true, null),
  ('dormitorio', 'Almohadones', 'Almohadón Bouclé', 'Almohadón en tela bouclé ultra suave', 'Blanco', '50x50 cm', 'Bouclé', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/almohadon_blanco_boucl%C3%A9.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Almohadón+Bouclé', true, null),
  ('dormitorio', 'Almohadones', 'Almohadón Natural', 'Almohadón en tonos naturales y tierra', 'Beige', '50x50 cm', 'Lino', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/almohadones_beige_natural.jpg', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/almohadones_camel_sofa.jpg', 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Almohadón+Natural', true, null),
  ('bano', 'Toallas', 'Toalla de Cuerpo', 'Toalla suave y absorbente de uso diario', 'Amarillo', 'Cuerpo', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/toallas_amarillo_azul_apiladlas.jpg', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/toallas_amarillo_azul_2.jpg', 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Toalla+de+Cuerpo', true, null),
  ('bano', 'Toallas', 'Toalla de Cuerpo', 'Toalla suave y absorbente de uso diario', 'Azul', 'Cuerpo', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/toallas_amarillo_azul_apiladlas.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Toalla+de+Cuerpo', true, null),
  ('bano', 'Toallas', 'Toalla de Cuerpo', 'Toalla suave y absorbente de uso diario', 'Amarillo', 'Cuerpo', 'Algodón rizado', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/toallas_amarillas_apiladas.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Toalla+de+Cuerpo', true, null),
  ('bano', 'Toallas', 'Toalla a Rayas', 'Toalla con diseño a rayas decorativa', 'Azul/Blanco', 'Cuerpo', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/toallas_rayas_azul.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Toalla+a+Rayas', true, null),
  ('bano', 'Toallas', 'Toalla Clásica', 'Toalla blanca clásica, ideal para regalo', 'Blanco', 'Cuerpo', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/toallas_blancas_apiladas.jpg', null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Toalla+Clásica', true, null),
  ('bano', 'Batas', 'Bata de Baño', 'Bata suave y absorbente para uso diario', 'Blanco', 'Talle único', 'Algodón', null, null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Bata+de+Baño', true, null),
  ('bano', 'Recipientes para el Baño', 'Set Recipientes Baño', 'Set de recipientes para jabón y cepillo de dientes', 'Blanco', 'Estándar', 'Cerámica', null, null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Set+Recipientes+Baño', true, null),
  ('cocina', 'Manteles', 'Mantel a Rayas', 'Mantel con diseño a rayas, lavable', 'Azul/Blanco', '140x180 cm', 'Algodón', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/mantel_rayas_mesa.jpg', 'https://jurrjepginryykszcqrq.supabase.co/storage/v1/object/public/productos/mantel_rayas_detalle.jpg', 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Mantel+a+Rayas', true, null),
  ('decoracion', 'Decorativos para Pared', 'Estrella de Macramé', 'Decorativo para pared en forma de estrella con flecos', 'Natural', '40 cm', 'Yute/Macramé', null, null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Estrella+de+Macramé', true, null),
  ('organizacion', 'Guardadores / Neceser', 'Bolso Estrella', 'Bolso guardador con estrella bordada, multifunción', 'Natural', 'Mediano', 'Tela', null, null, 'https://wa.me/543513450795?text=Hola!+Quiero+consultar+por+Bolso+Estrella', true, null)
;
